//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2
use serde::{Deserialize, Serialize};
use sea_orm::entity::prelude::*;
use uuid::Uuid;
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize)]
#[sea_orm(schema_name = "us_market_insights", table_name = "shippers")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub shipper_type: String,
    #[sea_orm(column_type = "Text")]
    pub company_name: String,
    #[sea_orm(column_type = "Text")]
    pub street_address: String,
    #[sea_orm(column_type = "Text")]
    pub city: String,
    #[sea_orm(column_type = "Text")]
    pub state: String,
    #[sea_orm(column_type = "Text")]
    pub zip_code: String,
    #[sea_orm(column_type = "Text")]
    pub phone: String,
    #[sea_orm(column_type = "Text")]
    pub fax: String,
    #[sea_orm(column_type = "Text")]
    pub sales: String,
    #[sea_orm(column_type = "Text")]
    pub industry: String,
    #[sea_orm(column_type = "Text")]
    pub website: String,
    #[sea_orm(column_type = "Text")]
    pub first_name: String,
    #[sea_orm(column_type = "Text")]
    pub last_name: String,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    #[sea_orm(column_type = "Text")]
    pub email: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
