//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "us_market_insights", table_name = "us_zoom_info")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub domain: String,
    #[sea_orm(column_type = "Text")]
    pub pattern: String,
    #[sea_orm(column_type = "Text")]
    pub first_name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub middle_name: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub last_name: String,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    #[sea_orm(column_type = "Text")]
    pub company_name: String,
    #[sea_orm(column_type = "Text")]
    pub mailing_address: String,
    #[sea_orm(column_type = "Text")]
    pub primary_city: String,
    #[sea_orm(column_type = "Text")]
    pub primary_state: String,
    #[sea_orm(column_type = "Text")]
    pub zip_code: String,
    #[sea_orm(column_type = "Text")]
    pub country: String,
    #[sea_orm(column_type = "Text")]
    pub phone: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub web_address: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub email: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub revenue: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub employee: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub industry: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub sub_industry: Option<String>,
    pub created_date: Option<DateTime>,
    #[sea_orm(column_type = "Text", nullable)]
    pub file_of_origin: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
