//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(
    schema_name = "us_market_insights",
    table_name = "us_business_credit_analysis"
)]
pub struct Model {
    #[sea_orm(column_type = "Text")]
    pub business_type: String,
    #[sea_orm(column_type = "Text")]
    pub sales_volume: String,
    #[sea_orm(column_type = "Text")]
    pub credit_score: String,
    pub number_of_companies: i32,
    #[sea_orm(column_type = "Text")]
    pub dataset: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
